# Basic
name:               "mieczkowski Lab"
title:              "Mieczkowski lab at Medical University in Gdansk"
description:        "this is a page for Jakub Mieczkowski lab, we are computational biology lab at the Medical University in Gdansk"

baseurl: https://bplisz.github.io/jakubmie.github.io/

# Highlighter
highlighter:        rouge

# Navigation
nav:

  - name:           "research"
    href:           "/research"
  - name:           "team"
    href:           "/team"
  - name:           "publications"
    href:           "/publications"
  - name:           "resources"
    href:           "/resources"
  - name:           "contact & join"
    href:           "/contactjoin"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "team"
    values:
      layout:       "profile"
  - 
    scope:
      path: _papers
      type: papers
    values:
      layout: paper
      sectionid: publications

collections:
  team:
    output: true
    permalink: /team/:title/index.html
  papers:
    output: true
    permalink: /papers/:year/:month/:day/:title/
